/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.unimontes.ccet.dcc.pg1.desktop.view;

import br.unimontes.ccet.dcc.pg1.desktop.controller.CadastrarUsuarioController;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author andre
 */
public class TelaCadastro extends javax.swing.JFrame {
    public TelaCadastro() {
        initComponents();
        
        Icon i = iconFechar.getIcon();
        ImageIcon icon = (ImageIcon)i;
        Image image = icon.getImage().getScaledInstance(iconFechar.getWidth(), iconFechar.getHeight(), Image.SCALE_SMOOTH);
        iconFechar.setIcon(new ImageIcon(image));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelCadastro = new br.unimontes.ccet.dcc.pg1.desktop.view.paineis.Painel();
        pCadastro = new br.unimontes.ccet.dcc.pg1.desktop.view.componentes.RoundContainer();
        tfUser = new br.unimontes.ccet.dcc.pg1.desktop.view.componentes.TextFields.UserTextField();
        labelApp = new javax.swing.JLabel();
        tfNome = new br.unimontes.ccet.dcc.pg1.desktop.view.componentes.TextFields.NomeTextField();
        ptfSenha = new br.unimontes.ccet.dcc.pg1.desktop.view.componentes.TextFields.PasswordField();
        btCadastrar = new br.unimontes.ccet.dcc.pg1.desktop.view.componentes.Buttons.RoundButton();
        labelNome = new javax.swing.JLabel();
        labelUser = new javax.swing.JLabel();
        labelSenha = new javax.swing.JLabel();
        iconFechar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        painelCadastro.setBackground(new java.awt.Color(82, 82, 140));

        pCadastro.setBackground(new java.awt.Color(204, 204, 204));
        pCadastro.setName("pCadastro"); // NOI18N
        pCadastro.setPreferredSize(new java.awt.Dimension(350, 300));
        pCadastro.setRaio(25);

        tfUser.setBackground(new java.awt.Color(255, 255, 255));
        tfUser.setName("tfUser"); // NOI18N
        tfUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfUserKeyReleased(evt);
            }
        });

        labelApp.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        labelApp.setForeground(new java.awt.Color(102, 0, 102));
        labelApp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelApp.setText("cursIN");
        labelApp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        tfNome.setBackground(new java.awt.Color(255, 255, 255));
        tfNome.setName("tfNome"); // NOI18N
        tfNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfNomeKeyReleased(evt);
            }
        });

        ptfSenha.setBackground(new java.awt.Color(255, 255, 255));
        ptfSenha.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        ptfSenha.setName("ptfSenha"); // NOI18N
        ptfSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ptfSenhaKeyReleased(evt);
            }
        });

        btCadastrar.setText("CADASTRAR");
        btCadastrar.setEnabled(false);
        btCadastrar.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        btCadastrar.setName("btCadastrar"); // NOI18N
        btCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarActionPerformed(evt);
            }
        });

        labelNome.setFont(new java.awt.Font("Trench", 1, 14)); // NOI18N
        labelNome.setForeground(new java.awt.Color(102, 0, 102));
        labelNome.setText("Nome");

        labelUser.setFont(new java.awt.Font("Trench", 1, 14)); // NOI18N
        labelUser.setForeground(new java.awt.Color(102, 0, 102));
        labelUser.setText("Username");

        labelSenha.setFont(new java.awt.Font("Trench", 1, 14)); // NOI18N
        labelSenha.setForeground(new java.awt.Color(102, 0, 102));
        labelSenha.setText("Senha");

        iconFechar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/unimontes/ccet/dcc/pg1/desktop/view/util/icons/fechar.png"))); // NOI18N
        iconFechar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        iconFechar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        iconFechar.setName("iconFechar"); // NOI18N
        iconFechar.setPreferredSize(new java.awt.Dimension(30, 30));
        iconFechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconFecharMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pCadastroLayout = new javax.swing.GroupLayout(pCadastro);
        pCadastro.setLayout(pCadastroLayout);
        pCadastroLayout.setHorizontalGroup(
            pCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCadastroLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(pCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pCadastroLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(labelApp, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(iconFechar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(pCadastroLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(labelNome))
            .addGroup(pCadastroLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pCadastroLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(labelUser))
            .addGroup(pCadastroLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(pCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfUser, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelSenha)
                    .addComponent(ptfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(btCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pCadastroLayout.setVerticalGroup(
            pCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCadastroLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(pCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pCadastroLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(labelApp))
                    .addComponent(iconFechar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(labelNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pCadastroLayout.createSequentialGroup()
                        .addComponent(tfUser, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelSenha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ptfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pCadastroLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(btCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        javax.swing.GroupLayout painelCadastroLayout = new javax.swing.GroupLayout(painelCadastro);
        painelCadastro.setLayout(painelCadastroLayout);
        painelCadastroLayout.setHorizontalGroup(
            painelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelCadastroLayout.createSequentialGroup()
                .addContainerGap(225, Short.MAX_VALUE)
                .addComponent(pCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(225, 225, 225))
        );
        painelCadastroLayout.setVerticalGroup(
            painelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCadastroLayout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(pCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(150, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarActionPerformed
        btCadastrar.setEnabled(false);
        if(CadastrarUsuarioController.executa(pCadastro) == 1){
            new TelaPrincipal().setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_btCadastrarActionPerformed

    private void iconFecharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconFecharMouseClicked
        new TelaPrincipal().setVisible(true);
        dispose();
    }//GEN-LAST:event_iconFecharMouseClicked

    private void tfNomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNomeKeyReleased
        if((tfNome.getText().isBlank() == false || tfNome.getText().isEmpty() == false)
                &&(tfUser.getText().isBlank() == false || tfUser.getText().isEmpty() == false)
                &&(ptfSenha.getText()).isBlank() == false || ptfSenha.getText().isEmpty() == false){
            btCadastrar.setEnabled(true);
        }
    }//GEN-LAST:event_tfNomeKeyReleased

    private void tfUserKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfUserKeyReleased
        if((tfNome.getText().isBlank() == false || tfNome.getText().isEmpty() == false)
                &&(tfUser.getText().isBlank() == false || tfUser.getText().isEmpty() == false)
                &&(ptfSenha.getText()).isBlank() == false || ptfSenha.getText().isEmpty() == false){
            btCadastrar.setEnabled(true);
        }
    }//GEN-LAST:event_tfUserKeyReleased

    private void ptfSenhaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ptfSenhaKeyReleased
        if((tfNome.getText().isBlank() == false || tfNome.getText().isEmpty() == false)
                &&(tfUser.getText().isBlank() == false || tfUser.getText().isEmpty() == false)
                &&(ptfSenha.getText()).isBlank() == false || ptfSenha.getText().isEmpty() == false){
            btCadastrar.setEnabled(true);
        }
    }//GEN-LAST:event_ptfSenhaKeyReleased

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private br.unimontes.ccet.dcc.pg1.desktop.view.componentes.Buttons.RoundButton btCadastrar;
    private javax.swing.JLabel iconFechar;
    private javax.swing.JLabel labelApp;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelSenha;
    private javax.swing.JLabel labelUser;
    private br.unimontes.ccet.dcc.pg1.desktop.view.componentes.RoundContainer pCadastro;
    private br.unimontes.ccet.dcc.pg1.desktop.view.paineis.Painel painelCadastro;
    private br.unimontes.ccet.dcc.pg1.desktop.view.componentes.TextFields.PasswordField ptfSenha;
    private br.unimontes.ccet.dcc.pg1.desktop.view.componentes.TextFields.NomeTextField tfNome;
    private br.unimontes.ccet.dcc.pg1.desktop.view.componentes.TextFields.UserTextField tfUser;
    // End of variables declaration//GEN-END:variables
}
